-- MySQL Script generated by MySQL Workbench
-- Thu Apr  3 22:59:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Engenheiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Engenheiro` (
  `CodEng` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodEng`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projeto` (
  `CodProj` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodProj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Engenheiro_has_Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Engenheiro_has_Projeto` (
  `Engenheiro_CodEng` INT NOT NULL,
  `Projeto_CodProj` INT NOT NULL,
  `Funcao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Engenheiro_CodEng`, `Projeto_CodProj`),
  INDEX `fk_Engenheiro_has_Projeto_Projeto1_idx` (`Projeto_CodProj` ASC) VISIBLE,
  INDEX `fk_Engenheiro_has_Projeto_Engenheiro_idx` (`Engenheiro_CodEng` ASC) VISIBLE,
  CONSTRAINT `fk_Engenheiro_has_Projeto_Engenheiro`
    FOREIGN KEY (`Engenheiro_CodEng`)
    REFERENCES `mydb`.`Engenheiro` (`CodEng`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Engenheiro_has_Projeto_Projeto1`
    FOREIGN KEY (`Projeto_CodProj`)
    REFERENCES `mydb`.`Projeto` (`CodProj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
